# -*- coding: iso8859-15 -*-
#
# Generated by csv2rules.py    *** DO NOT EDIT ***

DUTRules = [ DUTRule(p, c) for (p,c) in (
# Prev.	Assiduité	Moy Gen	Barres UE	Comp prev/cur	Code SEM	Codes UE	Code prev. (si modifié)	Devenir	Action	Explication
# Semestre prec. validé:
( ((None, ADM, ADC, ADJ), True, True, True, ALL),
  (ADM, (ADM,), None, NEXT, None, 'Passage normal') ),
( ((None, ADM, ADC, ADJ), True, False, True, ALL),
  (ATT, (ADM,), None, NEXT, None, 'Pas moy: attente suivant pour compenser') ),
( ((None, ADM, ADC, ADJ), True, ALL, False, ALL),
  (ATB, (ADM, AJ), None, NEXT, None, 'Pas barre UE') ),
( ((None, ADM, ADC, ADJ), False, ALL, ALL, ALL),
  (ATJ, (AJ,), None, NEXT, None, 'Pb assiduité') ),
( ((ADM, ADJ), ALL, False, ALL, True),
  (ADC, (ADM, CMP), None, NEXT, None, 'Compense avec semestre précédent') ),
# Semestre prec. ATJ (pb assiduité):
( ((ATJ,), ALL, ALL, ALL, ALL),
  (NAR, (AJ,), NAR, REO, None, 'pb assiduité persistant: réorientation') ),
( ((ATJ,), ALL, ALL, ALL, ALL),
  (AJ, (AJ,), AJ, REDOANNEE, None, 'pb assiduité persistant: redoublement année') ),
# ATJ	*	*	*	*
# Semestre prec. ATT (pb moy gen):
( ((ATT,), True, True, True, True),
  (ADM, (ADM,), ADC, NEXT, None, 'passage, et compense précédent') ),
( ((ATT,), True, True, True, ALL),
  (ADM, (ADJ,), ADM, NEXT, None, 'passage, le jury valide precedent') ),
( ((ATT,), False, True, True, ALL),
  (ATJ, (AJ,), ADJ, NEXT, None, 'passage, le jury valide précédent, pb assiduité') ),
( ((ATT,), True, False, ALL, ALL),
  (AJ, (AJ,), AJ, REDOANNEE, None, 'redoublement année') ),
( ((ATT,), ALL, True, True, False),
  (AJ, (AJ,), AJ, REDOANNEE, None, 'pas de compensation ni validation du précédent') ),
# Semestre prec. ATB (pb barre UE):
( ((ATB,), ALL, ALL, ALL, ALL),
  (AJ, (ADM, AJ), AJ, REDOANNEE, None, 'prev ne peut pas être validé, redoublement année') ),
( ((ATB,), ALL, ALL, ALL, ALL),
  (NAR, (ADM, AJ), NAR, REO, None, 'prev ne peut pas être validé, réorientation') ),
( ((ATB,), True, True, True, ALL),
  (ADM, (ADM,), ADJ, None, None, 'le jury valide prev') ),
( ((ATB,), True, False, True, ALL),
  (ATT, (ADM, AJ), ADJ, None, None, 'le jury valide prev, pas moyenne gen., attente suivant') ),
( ((ATB,), True, ALL, False, ALL),
  (ATB, (ADM, AJ), ADJ, None, None, 'le jury valide prev, pb barre UE, attente') ),
( ((ATB,), False, ALL, ALL, ALL),
  (ATJ, (AJ,), ADJ, None, None, 'le jury valide prev, mais probleme assiduité.') ),
# Semestre prec. AJ (ajourné):
( ((AJ,), ALL, ALL, ALL, ALL),
  (None, (), None, None, BUG, 'impossible') ),
)]
