# -*- coding: iso8859-15 -*-
#
# Generated by csv2rules.py    *** DO NOT EDIT ***
#
# Command: ./csv2rules.py misc/parcoursDUT.csv
# 
from sco_codes_parcours import *

rules_source_file='misc/parcoursDUT.csv'

DUTRules = [ DUTRule(p, c) for (p,c) in (
# Prev.	Assiduité	Moy Gen	Barres UE	Comp prev/cur	Suivant	Code SEM	Codes UE	Code prev. (si modifié)	Devenir	Action	Explication
# Semestre prec. validé:
( ((None, ADM, ADC, ADJ), True, True, True, ALL, ALL),
  (ADM, (ADM,), None, NEXT, None, 'Passage normal') ),
( ((None, ADM, ADC, ADJ), True, False, True, ALL, True),
  (ATT, (ADM,), None, NEXT, None, 'Pas moy: attente suivant pour compenser') ),
( ((None, ADM, ADC, ADJ), True, ALL, False, ALL, ALL),
  (ATB, (ADM, AJ), None, NEXT, None, 'Pas barre UE') ),
( ((None, ADM, ADC, ADJ), False, ALL, ALL, ALL, True),
  (ATJ, (AJ,), None, NEXT, None, 'Pb assiduité, passe sans valider pour l\'instant') ),
( ((ADM, ADJ), True, False, ALL, True, ALL),
  (ADC, (ADM, CMP), None, NEXT, None, 'Compense avec semestre précédent') ),
# Semestre prec. ATJ (pb assiduité):
( ((ATJ,), False, ALL, ALL, ALL, ALL),
  (NAR, (AJ,), AJ, REO, None, 'Pb assiduité persistant: réorientation') ),
( ((ATJ,), False, ALL, ALL, ALL, ALL),
  (AJ, (AJ,), AJ, REDOANNEE, None, 'Pb assiduité persistant: redoublement année') ),
( ((ALL,), False, ALL, ALL, ALL, ALL),
  (AJ, (), ADM, REO, None, 'Pb assiduité, étudiant en échec.') ),
# Semestre prec. ATT (pb moy gen):
( ((ATT,), True, True, True, True, ALL),
  (ADM, (ADM,), ADC, NEXT, None, 'Passage, et compense précédent') ),
( ((ATT,), True, True, True, ALL, ALL),
  (ADM, (ADJ,), ADJ, NEXT, None, 'Passage, le jury valide precedent') ),
( ((ATT,), False, True, True, ALL, True),
  (ATJ, (AJ,), ADJ, NEXT, None, 'Passage, le jury valide précédent, pb assiduité') ),
( ((ATT,), True, False, ALL, ALL, ALL),
  (AJ, (AJ,), AJ, REDOANNEE, None, 'Redoublement année') ),
( ((ATT,), ALL, True, True, False, ALL),
  (AJ, (AJ,), AJ, REDOANNEE, None, 'Pas de compensation ni validation du précédent') ),
# Semestre prec. ATB (pb barre UE):
( ((ATB,), ALL, ALL, ALL, ALL, ALL),
  (AJ, (ADM, AJ), AJ, REDOANNEE, None, 'Prev ne peut pas être validé, redoublement année') ),
( ((ATB,), ALL, ALL, ALL, ALL, ALL),
  (NAR, (ADM, AJ), NAR, REO, None, 'Prev ne peut pas être validé, réorientation') ),
( ((ATB,), True, True, True, ALL, ALL),
  (ADM, (ADM,), ADJ, None, None, 'Le jury valide prev') ),
( ((ATB,), True, False, True, ALL, True),
  (ATT, (ADM, AJ), ADJ, None, None, 'Le jury valide prev, pas moyenne gen., attente suivant') ),
( ((ATB,), True, ALL, False, ALL, True),
  (ATB, (ADM, AJ), ADJ, None, None, 'Le jury valide prev, pb barre UE, attente') ),
( ((ATB,), False, ALL, ALL, ALL, True),
  (ATJ, (AJ,), ADJ, None, None, 'Le jury valide prev, mais probleme assiduité.') ),
# Semestre prec. AJ (ajourné):
( ((AJ,), True, False, ALL, ALL, ALL),
  (AJ, (), None, REDOANNEE, None, 'Echec de 2 semestres, redouble année') ),
( ((AJ,), True, True, False, ALL, ALL),
  (AJ, (), None, REDOANNEE, None, 'Echec de 2 semestres, redouble année') ),
( ((NAR,), ALL, ALL, ALL, ALL, ALL),
  (BUG, (BUG,), None, BUG, BUG, 'Situation impossible !') ),
# Décisions du jury:
( ((ALL,), True, False, ALL, ALL, ALL),
  (ADJ, (ADM,CMP), None, NEXT, None, 'Le jury décide de valider') ),
( ((ATT,ATB), True, False, ALL, ALL, ALL),
  (ADJ, (ADM,CMP), ADJ, NEXT, None, 'Le jury décide de valider ce semestre et le précédent') ),
( ((ALL,), True, True, False, ALL, ALL),
  (ADJ, (ADM,CMP), None, NEXT, None, 'Le jury décide de valider') ),
( ((ATT,ATB), True, True, False, ALL, ALL),
  (ADJ, (ADM,CMP), ADJ, NEXT, None, 'Le jury décide de valider ce semestre et le précédent') ),
( ((ATT,ATB), False, False, True, ALL, True),
  (ATT, (ADM, AJ), ADJ, NEXT, None, 'Pb moy: attente, mais le jury valide le précédent') ),
# Semestres "décales" (REDOSEM)
( ((None, ADM, ADC, ADJ), True, False, ALL, False, ALL),
  (AJ, (), None, REDOSEM, None, 'Pas moy: redouble ce semestre') ),
( ((None, ADM, ADC, ADJ), True, True, False, False, ALL),
  (AJ, (), None, REDOSEM, None, 'Pas barre UE: redouble ce semestre') ),
( ((None, ADM, ADC, ADJ), False, ALL, ALL, ALL, ALL),
  (AJ, (), None, REDOSEM, None, 'Pb assiduité: redouble ce semestre') ),
# Exclusion (art. 22): si precedent non valide et pas les barres dans le courant, on peut ne pas autoriser a redoubler:
# (le cas ATB est couvert plus haut)
( ((AJ,ATT,NAR), True, False, ALL, ALL, ALL),
  (NAR, (), NAR, REO, None, 'Non autorisé à redoubler') ),
( ((AJ,ATT,NAR), True, True, False, ALL, ALL),
  (NAR, (), NAR, REO, None, 'Non autorisé à redoubler') ),
)]
