DEST = /www/zope/zope2/lib/python/Products/ZRadius

INSTOPTS = -g zope -o zope 

all:
	echo Stoopid

install:
	install -d ${INSTOPTS} -m 750 ${DEST}
	install ${INSTOPTS} -m 640 *.py *.txt *.dtml *.gif ${DEST}

